// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[shortcode].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/admin/_middleware.ts";
import * as $3 from "./routes/admin/deleteAll.ts";
import * as $4 from "./routes/admin/index.tsx";
import * as $5 from "./routes/api/joke.ts";
import * as $6 from "./routes/api/links.ts";
import * as $7 from "./routes/developers.tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/login.tsx";
import * as $10 from "./routes/stats.tsx";
import * as $$0 from "./islands/CopyButton.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/CreateLink.tsx";
import * as $$3 from "./islands/DeleteAll.tsx";
import * as $$4 from "./islands/DynamicLinkList.tsx";
import * as $$5 from "./islands/SignIn.tsx";

const manifest = {
  routes: {
    "./routes/[shortcode].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/admin/_middleware.ts": $2,
    "./routes/admin/deleteAll.ts": $3,
    "./routes/admin/index.tsx": $4,
    "./routes/api/joke.ts": $5,
    "./routes/api/links.ts": $6,
    "./routes/developers.tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/login.tsx": $9,
    "./routes/stats.tsx": $10,
  },
  islands: {
    "./islands/CopyButton.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/CreateLink.tsx": $$2,
    "./islands/DeleteAll.tsx": $$3,
    "./islands/DynamicLinkList.tsx": $$4,
    "./islands/SignIn.tsx": $$5,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
